### PR TITLE
Added pub_map_odom_transform parameter (when provide_odom_frame is true)

### PR DESCRIPTION
**Pull request by davidbsp**
Solved issue https://github.com/googlecartographer/cartographer_ros/issues/1417.
Hope this can be merged to the main repo.

### CODE REVIEW

**Comment by davidbsp** [comment]
@googlebot I signed it!

**Comment by MichaelGrupp** [comment]
I don't yet understand why one would need this, but maybe you can achieve what you want with the existing parameters already.

E.g. this config will directly publish map->base_link without publishing (or requiring) map->odom:

```lua
...

  map_frame = "map",
  tracking_frame = "base_link",
  published_frame = "base_link",
  odom_frame = "<unused>",
  provide_odom_frame = false,

...
```

Or, as a more odd config, if you then change `map_frame = odom` it should only publish odom->base_link. But IMO this only makes sense if Cartographer runs in a "pure odometry" mode with loop closure disabled.

**Comment by davidbsp** [comment]
Hi @MichaelGrupp, thank you for the feedback.

The rationale behind this would be to use cartographer to provide pure local odometry, so we can use another approach at the higher level to provide global discrete localization. 

This would, for example, allow for an architecture that is robust to GPS dropouts (cartographer stops publishing poses if GPS dropouts occur).

The map->base_link solution wouldn't fit, as it would provide discrete pose jumps. 
However, your second suggestion makes sense (never occurred to me tbh). Will test it some day.

Cheers.

**Comment by MichaelGrupp** [comment]
Closing this for now.

**Pull request closed without merging**
