### PR TITLE
ROS 2 Cartographer ROS port

### PR DESCRIPTION
**Pull request by clalancette**
This PR is a port of cartographer_ros to ROS 2.  As you can see from the diff, it is actually quite a substantial change to cartographer_ros to make this work for ROS 2.

This code has been used in a few different robotics projects, so we know that at least the major parts of it work.  There are some parts of it that could use a cleanup, as they workaround problems that may or may not still exist.

As-is, this PR doesn't apply to master.  That's because this port was originally done against the 1.0.0 tag of this repository.  Moving it forward would be possible, but would likely require quite a bit of work.

I'm opening this PR as a starting point for the discussion on how to move this code into the upstream.  Some steps that seem obvious to me:

1.  Update this to apply against master.
1.  Create a ros2 branch for this to target

There is also the open question on whether the cartographer project is willing to take over maintenance of this port and maintain/release it for ROS 2 distributions going forward.

Finally, I'll note that I don't have too much of time to devote to this.  I'm doing this on discretionary time, so while I'm glad to do some simple work here, I won't have the time to do any major refactoring (like updating it to master).

Comments, questions, thoughts all welcome!

### CODE REVIEW

**Comment by bochen87** [comment]
Thank you @clalancette for the PR! 
If I understood correctly, we wanted to leave the master branch at this repository on ROS1 and merge the ROS2 into dedicated branches for this, i.e. create a dashing branch here and just push it into that branch.

**Comment by clalancette** [comment]
> If I understood correctly, we wanted to leave the master branch at this repository on ROS1 and merge the ROS2 into dedicated branches for this, i.e. create a dashing branch here and just push it into that branch.

Yep, that sounds good to me.  If you could please create a dashing branch for me, I can retarget this PR to that branch.

**Comment by bochen87** [comment]
> > If I understood correctly, we wanted to leave the master branch at this repository on ROS1 and merge the ROS2 into dedicated branches for this, i.e. create a dashing branch here and just push it into that branch.
> 
> Yep, that sounds good to me. If you could please create a dashing branch for me, I can retarget this PR to that branch.

I created the dashing branch

**Comment by clalancette** [comment]
> I created the dashing branch

Thanks, appreciated.  I've retargeted the PR to dashing now.

**Pull request closed without merging**
