### PR TITLE
Update assets_writer.rst

### PR DESCRIPTION
**Pull request by Geonhee-LEE**
I detected repetition sentence 'can be'

### CODE REVIEW

**Review by MichaelGrupp — APPROVED** [review]

**Comment by Geonhee-LEE** [comment]
@googlebot I signed it!

**Comment by MichaelGrupp** [comment]
Hi @Geonhee-LEE, sorry for the confusion. We have removed the Google CLA and replaced it with a "Developer Certificate of Origin". This requires that you use git with `--signoff`. Unfortunately I merged master which makes it a bit more complicated. Can you please do the following commands:

```bash
git clone https://github.com/Geonhee-LEE/cartographer_ros.git
cd cartographer_ros
git checkout patch-1
git remote add upstream https://github.com/cartographer-project/cartographer_ros.git
git rebase upstream/master --signoff
git push --force
```

This will allow me to merge it. Thanks a lot!

**Comment by Geonhee-LEE** [comment]
@MichaelGrupp  Hi! I'm done. Thanks for your detailed instructions.

**Comment by MichaelGrupp** [comment]
Thank you for the correction.

**Pull request merged**
