### PR TITLE
Fix typos in algo_walkthrough.rst

### PR DESCRIPTION
**Pull request by zhenzhenxiang**
Fix typos.

### CODE REVIEW

**Comment by johuber** [comment]
Good catch, thanks for fixing this!

 you will have to sign off the commit, best with:
`git commit --signoff --amend`
Also can you rebase this to the `master` branch, please?

 and then force push one more time!

**Comment by zhenzhenxiang** [comment]
> Good catch, thanks for fixing this!
> 
> you will have to sign off the commit, best with:
> `git commit --signoff --amend`
> Also can you rebase this to the `master` branch, please?
> 
> and then force push one more time!

I'm not sure whether I did it correctly, since this is my first time. 😃

**Review by johuber — APPROVED** [review]

**Comment by johuber** [comment]
> > Good catch, thanks for fixing this!
> > you will have to sign off the commit, best with:
> > `git commit --signoff --amend`
> > Also can you rebase this to the `master` branch, please?
> > and then force push one more time!
> 
> I'm not sure whether I did it correctly, since this is my first time. smiley

well you did not quite do what I expected but it still worked out :)

With rebase I meant to do:
```
git rebase origin/master
``` 
and then
```
git push --force
```

Thanks for fixing this!

**Comment by MichaelGrupp** [comment]
@johuber If you click on the "details" link of the DCO check, it shows you a page with exact instructions how to sign all the commits. I usually just tell the commiter to have a look there, it's easier.

**Pull request merged**
