### PR TITLE
Fix build status on front page.

### PR DESCRIPTION
**Pull request by wohe**
Changes "googlecartographer" to "cartographer-project"
for references to CI and GitHub.

Following cartographer-project/cartographer#1693.

Signed-off-by: Wolfgang Hess <whess@lyft.com>

### CODE REVIEW

**Comment by bochen87** [comment]
@wohe i also noticed that build is broken for melodic. #1319 describes the exact issue. however, i don't really know how to fix it

**Comment by bochen87** [comment]
nvm, i think i figured it out. will provide a PR to fix.

**Comment by bochen87** [comment]
can you rebase please? also, do we want to just delete the indigo and lunar docker files maybe since both are EOL?

**Comment by wohe** [comment]
@bochen87 done

**Comment by bochen87** [comment]
> @bochen87 done

Thanks! Somehow the CI hooks messed up - will try to close and re-open to trigger again.

**Pull request merged**
